### PR TITLE
create popup

### PR DESCRIPTION
**Pull request by AbbyNyakara**
Create a window popup.

- When the user clicks on the see more button, a popup window should appear. 
- The cards should be created dynamically in javascript 

P/S My partner's are unresponsive and im unable to get a hold of any of them

### CODE REVIEW

**Review by zainsadaqat — CHANGES_REQUESTED** [review]
# Required Changes 🔁
# Hello @AbbyNyakara  😄 

You're doing a great job on your project. We're proud of you. Good job so far! 

There are some issues that you still need to work on to go to the next project but you are almost there!

## Highlights
  ✅  Correct use of Github Flow
  ✅  No linter errors
  ✅  Descriptive Pull Request

## Required Changes ♻️

- [x] popup window on the mobile screen isn't responsive. As you can see, there's a horizontal scroll bar. Kindly make it responsive so that it fits on the mobile screen. 👍🏻 
Screen Shot 2022-05-20 at 9 42 19 PM

- [x] please add some padding around the content of the popup window so that it'll look clean and accessible. 👍🏻 
Screen Shot 2022-05-20 at 9 43 44 PM


_Check the comments under the review._




## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding! 👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by AbbyNyakara** [comment]
@zainsadaqat I have added a 20px padding around the popup and added the mobile responsiveness for the popup

**Review by zieeco — CHANGES_REQUESTED** [review]
Hi @AbbyNyakara 


Great work on making the changes requested by the previous reviewer 👏 
You've done well implementing some of the changes, however, there are some issues that you still need to work on to go to the next project, but you are almost there!


## To highlight 🎯

- No linter errors.✔️
- Nice design. ✔️
- Descriptive PR. ✔️


## Required Changes ♻️
- [ ] As required by the previous reviewer, the popup content of your mobile version is not responsive. Please, kindly fix this. see the video below :point_down: 

https://user-images.githubusercontent.com/59397159/169582054-05f63c14-00a7-494e-bceb-dc22dec74c5b.mp4






## Optional suggestions
- N/A

**_Every comment with the **[OPTIONAL]** prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._**


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by AbbyNyakara** [comment]
@zieeco , thanks for the correction. I had missed the mobile view. I only removed the horizontal scroll bars. Its now corrected

**Review by AmaduKamara — APPROVED** [review]
# Status: Approved 🟢🟢🟢 

Hi @AbbyNyakara

ClappingLeonardoDicaprioGIF (2)

Your project is complete!  There is nothing else to say other than... it's time to merge it: ship it:
Congratulations! 🎉 

## Highlights:
✅ Correct Github flow
✅ No linter error
✅ Good descriptive PR
✅ Modal looks great 👍 

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
```

**Pull request merged**
